<?php
namespace O4l3x4ndr3\SdkEasyCredito\Helpers\Enum;

enum AccountType: string
{
    case CONTA_CORRENTE_INDIVIDUAL = "CONTA_CORRENTE_INDIVIDUAL";
    case CONTA_CORRENTE_CONJUNTA = "CONTA_CORRENTE_CONJUNTA";
    case CONTA_POUPANCA_CONJUNTA = "CONTA_POUPANCA_CONJUNTA";
    case CONTA_POUPANCA_INDIVIDUAL = "CONTA_POUPANCA_INDIVIDUAL";
}