<?php
namespace O4l3x4ndr3\SdkEasyCredito\Helpers\Enum;

enum AccountType: string
{
    case CONTA_CORRENTE_INDIVIDUAL = "CONTA CORRENTE INDIVIDUAL";
    case CONTA_CORRENTE_CONJUNTA = "CONTA CORRENTE CONJUNTA";
    case CONTA_POUPANCA_CONJUNTA = "CONTA POUPANCA CONJUNTA";
    case CONTA_POUPANCA_INDIVIDUAL = "CONTA POUPANCA INDIVIDUAL";
}