<?php
namespace O4l3x4ndr3\SdkEasyCredito\Helpers\Enum;

enum CreditStatus: string
{
    case PRE_PROCESSAMENTO = "PRE_PROCESSAMENTO";
    case PRE_APROVADO = "PRE_APROVADO";
    case PENDENTE = "PENDENTE";
    case AGUARDANDO_DOCUMENTOS = "AGUARDANDO_DOCUMENTOS";
    case EM_ANALISE_MANUAL = "EM_ANALISE_MANUAL";
    case EM_ANALISE_OPERACIONAL = "EM_ANALISE_OPERACIONAL";
    case EM_ANALISE_DOCUMENTAL = "EM_ANALISE_DOCUMENTAL";
    case CONTRATADO = "CONTRATADO";
    case LIBERADO = "LIBERADO";
    case REPROVADO = "REPROVADO";
    case ESTORNO = "ESTORNO";
    case EXPIRADO = "EXPIRADO";
}