<?php
namespace O4l3x4ndr3\SdkEasyCredito\Helpers\Enum;

enum Education: string
{
    case NAO_ALFABETIZADO = "NAO_ALFABETIZADO";
    case ENSINO_FUNDAMENTAL_INCOMPLETO = "ENSINO_FUNDAMENTAL_INCOMPLETO";
    case ENSINO_FUNDAMENTAL_COMPLETO = "ENSINO_FUNDAMENTAL_COMPLETO";
    case ENSINO_MEDIO_INCOMPLETO = "ENSINO_MEDIO_INCOMPLETO";
    case ENSINO_MEDIO_COMPLETO = "ENSINO_MEDIO_COMPLETO";
    case ENSINO_SUPERIOR_INCOMPLETO = "ENSINO_SUPERIOR_INCOMPLETO";
    case ENSINO_SUPERIOR_COMPLETO = "ENSINO_SUPERIOR_COMPLETO";
    case POS_GRADUACAO = "POS_GRADUACAO";
}