<?php
namespace O4l3x4ndr3\SdkEasyCredito\Helpers\Enum;

enum Education: string
{
    case NAO_ALFABETIZADO = "NAO ALFABETIZADO";
    case ENSINO_FUNDAMENTAL_INCOMPLETO = "ENSINO FUNDAMENTAL INCOMPLETO";
    case ENSINO_FUNDAMENTAL_COMPLETO = "ENSINO FUNDAMENTAL COMPLETO";
    case ENSINO_MEDIO_INCOMPLETO = "ENSINO MEDIO INCOMPLETO";
    case ENSINO_MEDIO_COMPLETO = "ENSINO MEDIO COMPLETO";
    case ENSINO_SUPERIOR_INCOMPLETO = "ENSINO SUPERIOR INCOMPLETO";
    case ENSINO_SUPERIOR_COMPLETO = "ENSINO SUPERIOR COMPLETO";
    case POS_GRADUACAO = "POS GRADUACAO";
}