<?php
namespace O4l3x4ndr3\SdkEasyCredito\Helpers\Enum;

enum LoanObjectives: string
{
    case AJUDAR_UMA_OUTRA_PESSOA_DA_FAMILIA = "AJUDAR_UMA_OUTRA_PESSOA_DA_FAMILIA";
    case BELEZA_E_SAUDE = "BELEZA_E_SAUDE";
    case COMECAR_UM_NOVO_NEGOCIO = "COMECAR_UM_NOVO_NEGOCIO";
    case COMPRAR_CONSERTAR_UM_CARRO = "COMPRAR_CONSERTAR_UM_CARRO";
    case COMPRAR_REFORMAR_UMA_CASA = "COMPRAR_REFORMAR_UMA_CASA";
    case EDUCACAO = "EDUCACAO";
    case EVENTOS_FESTAS = "EVENTOS_FESTAS";
    case FAZER_COMPRAS = "FAZER_COMPRAS";
    case FERIAS_VIAGENS = "FERIAS_VIAGENS";
    case PAGAR_CONTAS = "PAGAR_CONTAS";
    case PAGAR_OUTRAS_DIVIDAS = "PAGAR_OUTRAS_DIVIDAS";
    case OUTRAS = "OUTRAS";
}