<?php
namespace O4l3x4ndr3\SdkEasyCredito\Helpers\Enum;
enum Occupation: string
{
    case APOSENTADO_PENSIONISTA = "APOSENTADO/PENSIONISTA";
    case AUTONOMO = "AUTONOMO";
    case EMPRESARIO = "EMPRESARIO";
    case PROFISSIONAL_LIBERAL = "PROFISSIONAL LIBERAL";
    case ASSALARIADO = "ASSALARIADO";
    case FUNCIONARIO_PUBLICO = "FUNCIONARIO PUBLICO";
    case DESEMPREGADO = "DESEMPREGADO";
}