<?php
defined('EASYCREDITO_ENVIRONMENT') or define('EASYCREDITO_ENVIRONMENT', $_SERVER['EASYCREDITO_ENVIRONMENT']);
defined('EASYCREDITO_SCOPE') or define('EASYCREDITO_SCOPE', $_SERVER['EASYCREDITO_SCOPE']);
defined('EASYCREDITO_CLIENT_ID') or define('EASYCREDITO_CLIENT_ID', $_SERVER['EASYCREDITO_CLIENT_ID']);
defined('EASYCREDITO_CLIENT_SECRET') or define('EASYCREDITO_CLIENT_SECRET', $_SERVER['EASYCREDITO_CLIENT_SECRET']);

defined('USER_AGENT') or define('USER_AGENT', 'SdkEasyCredito');
defined('CONTENT_TYPE_JSON') or define('CONTENT_TYPE_JSON', 'application/json');
defined('CONTENT_TYPE_URL_URLENCODED') or define('CONTENT_TYPE_URL_URLENCODED', 'application/x-www-form-urlencoded');
